sustrik/libmill

.gitignore

cleanup merge stuff

---

mill.c

All patches under the License-in==license-out policy; therefore MIT

Some compiler fixes: OS X and Xcode

---

tests/makefile

Make it easier for people to choose cc/gcc on systems where cc is clang.
Patch is MIT

Allow for cc/gcc selection

---

Makefile.am
perf/whispers.c

see https://en.wikipedia.org/wiki/Chinese_whispers
closes #28

add chinese whispers to perf examples.

---

debug.c
poller.c
tcp.c
tests/chan.c

god damn tabs
Also, we should consider adding a .clang-format file.

whitespace

---

CMakeLists.txt

this allows you to run:
```
cmake ..
make test
```
to configure, build everything, then run the tests :rocket: :octopus:

cmake tests

---

.gitignore
.travis.yml
readme.markdown
valbuf.c

add travis ci

---

documentation.html

new release updates! 
documenting changes to the API: 
• renamed `trace()` to `gotrace()`
• use new tcp deadline function signature in the docs, but we still need to mention something about the deadline parameter.

small update to docs

---

net.c

Apparently this one was lost in the udp merge.

Restore inet_pton fix

---

.travis.yml

this line stopped working, plus the one below it does a better job of what it was going for

remove useless line

---

poller.c

Replace duplicate pollset search loop with a helper without changing the
semantics.
Submitted under MIT/X11 license

Extract find_pollset helper

---

poller.c

Continue polling after interrupted system call

---

tests/sleep.c

Test that multiple msleep() works as expected

---

tests/chan.c

Test that sending or receiving with closed channel panics

---

stack.c

Fix build without stack guard

---

tests/signals.c

Fix int declaration inside of for loop

---

CMakeLists.txt

Fix function checks by resetting symbol requirements

---

.travis.yml
CMakeLists.txt

run a cmake build on each OS during integration test

add cmake to build matrix

---

AUTHORS

Add myself to AUTHORS file

---

tests/chan.c

Testing that child process panics generate unwanted and unhelpful core
dumps for successful tests. To avoid the core dumps these tests handle
now the SIGABRT and exit normally if libmill panics.
If libmill did not panic, the child process dump code so we can
investigate why it did not panic.

Avoid core dumps in panic tests

---

libmill.pc.in

https://github.com/sustrik/libmill/blob/master/configure.ac#L48

Fixes version in libmill.pc

---

tutorial/step7.c

This changes the code so that the forking of the child processes are done as intended i.e. from the parent.
Submitting under the MIT license.

Fix tutorial step 7

---

AUTHORS
ip.c

Sorry, i could test only [this line](https://github.com/sustrik/libmill/compare/master...antonmes:master?expand=1#diff-9057a6065f48975860ca814ef25354e0R350), but the rest seems logical.
Also i'm not sure how to write a test for this leak.
[before / after](https://cloud.githubusercontent.com/assets/5857728/15154770/5e0b9a8a-16f0-11e6-9980-a7b595c1846f.png)

Fix ipremote memory leaks

---

tests/tcp.c
tests/udp.c

The IP could be 192.168.14.1 etc.

Fix 'make check' if there are multiple ethernets

---

libmill.h
tcp.c
tests/tcp.c
tests/udp.c
tests/unix.c
udp.c
unix.c

Socket shutdown functions, this change is under MIT/X11 license

Socket shutdown
