sustrik/libmill

README.md

Confirmed that we now work on OS X 10.10.3. But clang is NOT supported due to gcc specific features... working on clang support.
Patch is MIT

OSX works w/ gcc but it must be a REAL gcc

---

index.html

posting a benchmark w/ suggested update to description:
```sh
23:17 $ ./perf/ctxswitch 45
performed 45M context switches in 0.924000 seconds
duration of one context switch: 20 ns
context switches per second: 50.000000M
```
```sh
✔  shark@rc /home/shark/libmill  [master|✔ ] 
23:29 $ ./perf/chr 20
received 20M messages in 1.004000 seconds
duration of receiving a single message: 50 ns
message received per second: 20.000000M
```

docs: update description

---

libmill.h
tcp.c

when binding to libmill from node.js (basically a C++ environment), i got:
```c++
error: typedef redefinition with different types ('struct tcpsock *' vs 'tcpsock')
```
the proposed change avoids the problem, allowing me to bind to libmill

avoid redefinition of typedef error on llvm

---

udp.c

`ss >= 0` is always true with ss declared as `size_t`.

Fix udprecv error handling

---

Makefile.am
libmill.h
tests/unix.c
unix.c

This is mostly c&p form tcp. By having a common fd+buffer struct the *recv/send functions could be unified.
There is a small API issue (if you care about linux abstract unix domain sockets that is). Abstract socket names start with 0 byte and that doesn't work well with the single char* addr argument we have now.

Unix socket support

---

libmill.h
tests/unix.c
unix.c

EINPROGRESS doesn't happen.
Alternatively we could handle EAGAIN and repeatedly try connect() until the
deadline is reached.

Remove deadline from unixconnect

---

unix.c

Don't clobber errno in unixconnects error path

---

poller.c

After suspend, the fd should be in the pollset. If it is not there this
must be a bug.
Add an assert that make the intent clear and fail loudly if this
assumption is wrong.

Assert that fd is found in pollset after suspend

---

utils.c

Currently we exit cleanly in mill_panic, loosing all state. Replace
exit() with abort(), creating a helpful core dump.
Submitted under MIT license.    

Abort on panic

---

libmill.h

This is an attempt to get rid of the unused-label warnings generated by the
choose block macros.
Unfortunately this only seems to work with clang. gcc still generates the
warnings.

(Try to) Silence unused label warnings inside choose blocks

---

tutorial/step2.c
tutorial/step3.c
tutorial/step4.c
tutorial/step5.c
tutorial/step6.c

The tutorial used to accept CR LF when receiving data, but sent LF. Now
we always use CR LF.

Use consistent with end of line terminator

---

Makefile.am
tests/signals.c

We run two coroutines, one sending signals to current process, and one
receiving them from a signal pipe. A signal handler is feeding received
signals into the pipe. To make the tests little harder, we create new
coroutines for each signal.

Add tests for mixing signals and coroutines

---

.travis.yml

looking at #83's travis tests happening now, i think we should `cat` the test-suite.log
if one day it's green on one OS but not the other, this way at least the report shows on travis

print test-suite.log on travis after fail

---

tests/chan.c

We should panic when waiting on a blocking channel that no other
coroutine is going to wake up. Add a test verifying this.

Tests that chr and chs panic on deadlock

---

configure.ac
stack.c

Compiling with -DMILL_ENABLE_STACK_GUARD=1 will mark the first
page of each goroutine stack as PROT_NONE. Not sure if it makes sense to
enable this by default, but it certainly makes it easier to debug stack
overflows.

Add optional stack guard page

---

stack.c
tests/tcp.c
tests/unix.c

- the base system gcc (4.2) doesn't have `__COUNTER__` support, but
clang from ports works.
- free() does a memset, so the stack guard has to be removed before calling it.
- SO_ACCEPTCON isn't supported so these tests are disabled.

Partial OpenBSD support

---

libmill.h
tcp.c
tests/tcp.c
tests/unix.c
unix.c

SO_ACCEPTCONN does not work on a lot of system, so add an explicit argument to
tcp/unixattach.
Tests now pass on OpenBSD, NetBSD and DragonFly.
Fixes #108

Add listening arg to tcp/unixattach

---

.travis.yml
ip.c
libmill.h
tests/tcp.c
tests/udp.c

not sure if this implementation is acceptable nor whether it should go in the IP Address or UDP Library, but I think exporting something to this affect from `libmill.h` would be rather useful.
With udprecv on datagram packets, we pass `ipaddr *addr` pointer
```c
size_t udprecv(udpsock s, ipaddr *addr, void *buf, size_t len, int64_t deadline);
```
While this returns a size_t of the inbound packet, the `ipaddr *addr` pointer is also allocated like an `ipaddr ipremote()` for origin, and we can use the allocated pointer to send data back to client. 
If we need to establish different category protocol connections to origin or to holepunch clients, before we're done we can extract sender's public IP Address string from datagram's `ipaddr addr`:
~~`char *udpaddr(ipaddr addr);`~~
```c
char …
```

convert ip address string from sockaddr

---

utils.h

OS X (and possibly other BSD descendants) do save sigmask by default with `setjmp` and cause about a 7x slowdown. Seems modern linux doesn't unless specific compatibility defines are present.
I made a perf test that is a variant of whisper.c but more in line with standard message passing tests used in erlang go typically.
See:
C: https://gist.github.com/banks/ed49cfeb176842302441
Go: https://gist.github.com/banks/f825baf42ed44cd3e648
Before I was seeing about 7x slower for the C variant with all optimisations enabled under OS X and clang.
This patch brings libmill perf back into same ballpark (marginally quicker usually on my machine) as go.
If it's valuable, I'm happy to contribute the gist above as an additional performance test (or a replacement to whisper.c) for the repo.
I've not yet …

Explicitly don't save signal mask with setjmp.

---

libmill.h
tcp.c
tests/tcp.c

Hi,Sometimes we need to know the client's ip or port,For example,connection from 127.0.0.1 can pass the server,but 221.xx.xx.xx cann't,Or the port range from 1000~2000 can pass,others should Refuse(like a firewall).
So I add a ipaddr struct in mill_tcpconn,Use tcpconnip(tcpsock s) function can get the connection ip info.

mill_tcpconn add member ipaddr

---

.gitignore
AUTHORS
Makefile.am
file.c
libmill.h
tests/file.c

Signed-off-by: Paulo Faria <paulo.faria.rl@gmail.com>
I'm not sure about the naming. `mfile` could be named `file`, but I think that's dangerous. The functions could be renamed to `mfopen`, `mfclose`, `mftell`, etc.. though.
Submitted under MIT/X11 license

add file wrapper

---

tcp.c
udp.c

i think the logical not is only applied to the left hand side of this comparison, so this should be the same check

get rid of logical compare

---

libmill.h

For compatibility with C++ code, convert the anonymous struct used inside the MILL_CLAUSELEN macro `sizeof(struct{...})` to a typedef.
Using `in:' or 'out:' from C++ code inside a `choose` structure
leads to a 'anonymous type cannot be defined in a type specified'
compile time error.
Patch submitted under MIT/X11.
```
(anonymous struct at ./...:46:5)' cannot be defined in a type specifier
in(ch, int, val):
^
./vendor/libmill/libmill.h:221:30: note: expanded from macro 'in'
#define in(chan, type, name) mill_in((chan), type, name, __COUNTER__)
^
./vendor/libmill/libmill.h:207:48: note: expanded from macro
'mill_in'
char mill_concat(mill_clause, idx)[MILL_CLAUSELEN];\
^
./vendor/libmill/libmill.h:154:32: note: expanded from macro
'MILL_CLAUSELEN'
#define MILL_CLAUSELEN (sizeof(struct{void …
```

convert anonymous struct to typedef

---

libmill.h

* targets #117 with the `mill_` prefix on common names (e.g. `go`, `end`, `in`, `out`, `now`). For uniformity purposes, `choose`-related macros have also been prefixed.
* initial short macros triggered with the definition of `MILL_SHORT_MACROS`
* C++ guard added

Renames symbols for a better integration with other libraries.

---

libmill.h

Re-introduced the register clobbering in the x86-64 implementation of context switching as clang is less conservative than gcc.

Clobber all registers in context switching for compiler compatibility
